image: node

before_script:
- echo '//artifactory.cimpress.io/artifactory/api/npm/npm-release-local/:_authToken=${ARTIFACTORY_TOKEN}' >> .npmrc
- nodejs -v
- npm -v
- npm install

stages:
- build
- deployment

build job:
  stage: build
  script:
  - npm run code-check
  - npm run build
  artifacts:
    paths:
    - lib

deploy:
  stage: deployment
  only:
    refs:
    - master
  script:
  - npm publish --registry=https://artifactory.cimpress.io/artifactory/api/npm/npm-release-local/
