language: node_js
node_js:
- '8'
dist: trusty
sudo: false
branches:
  except:
  - results
install:
- npm install
script:
- npm run code-check
- npm run build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: gevr458n7wT/4MUTIwQWoEZotfj2SqHB7qMnNukGrTk+Pzu3flgTh1iYJIt3reUyDZfvgNdq5RWPnWS2bFUBsp+78rOI8oBE6bO/5Nn50DzhEmpv0+YKPZ3iS+1CKxOkus4a8hNKuJmccQ7VEvP28cujaJlWX4IdcNMRw6+AYlcAvgrbDxCfn1lnA0z9uaL0uVqC/20Sf6p+HGFi0R8+cMUmxG8Mo8/MSCdBA6QOKZSqoofx+s1xTsNtq+RwrkQXwxX+LmO+IvbJ0PlmzrM4I/+GBx1CkILkh48RqLHw7gxcBKTwq/UY2xlSINlYWiRPvkO3oSGKtKofKExX+6ueZVIsCpPu+t1Bmv1DrT67nlYvSyzlED7d8jUVtGB8F8d4oufgJFKcLLYr22rdX0Q9DSnuxtQD1HIlVswJ1zC1PdE9luvD0QBm0v20w/V4V0JPJQiZIyPYlRCUsgu5ILxTAMN4uMxPL5DjHNzyBE6uG5a7OTJhykGHMH7ECjgqSftDrvDpxxpqDDO72aiSWfFDmnN6aUuIx69H3aNzpio6L1r5+zYXxfhmfabEBJIl28uXzHlhUHr6LeoeIWrSPgRD6VyzdFpaR1M57lujv9d+XYRlnJHzpXywrHtXO085R0NtU/9xK22fiJy7Hv9sQ33hCo+o7SKa4UB+g6kuDNsk9Fg=
  on:
    branch: master
env:
  global:
  - secure: OH43g+O6Tueo+67Fj2m+pHcF0hUL+OKp2bkIqFTltrQ/AVZKwKIEOvWxsEqn4L3OUmCfR9y9pyRimv6x9JnZjLArb/DhvOSscVhWp02grQy4xOBYtYc5q5SlETz/MUbqJ7l9HWTF/YihuvTYSm2+jvsaO23PzQ1UdewvsQN9moEZ+H1e6Py+bscyjNhhOBI4W6vpWItKFAtnYG99fknad/JCP/n6x8MkCdWRXBmTghxqHJT/1NQdi9NG1V0oR3rzAQSvgSunuzt723XF3zGectM3iwDJuSFySwUe+Nb+r9eIoIYUNRXzvwKVMIRuCYnwd18fg/hWIV4bO19PIkkJhKt4/ebWEHLdB/5GXzwO8GdFqg3CKi2CIKI8COyvW9SvKIC9PrLrn6g7Ih6u+7EQoBe50oZNOStjFBdou0YZlHrAGEE3rqjgizag/K0kI+xrDYGWXAENqNA1oHTXcHROKbPI6iR6L4q+y0JxOjTTyxpWwu0eI5WFesEtPEX2ypDcuZkPzztuZnJoGyPcbzW7KYNyuNTi4Eor+hXVmf3OE71tewkHrgZw//Y1zOF7ZqC7YkfKRgN6i+m4BeKdJbaYLXBbkNzl6brS6jL6bg/bx2NQEDVhyI4UuOsLYC3fdmGfhOOcVIXoFFt9nbQ9W1/mM/HJyL5JPinUKULHlonLQks=
  - secure: XwGwQ+bx7p+438WqYMFMEVPtuRp/H8cdp74QHWYoOMfif8LiBJWBNsHEezDQMhscxHevIom9ZwdubatVGob7BZF21r+h/F+YX8eoWjNaCvfiv2XLRPkBU6sGP0PjwzVEBSt7Zi753IDuIeRM8CuhI7Qibe86Wya5h06z1C10uWn8arGinr74iSdqwXcFqraSl8ZjAYrg6qrlz4hZy6M/8RdrPFRVjnb4Ai5v4r2OfKKHfo3kpt1tvM+yQiXl6qAaI0laA4UJeaBvd9SFFtXzABz8bRBW24V2WqvBxRLp2s1jacWUsBJBvcgXK7drPH9xqP4SvUwYTC8mNraLokQvtzqt8tZ3ArBbao/upXK0b5AeO8TXPxdhCWjzOeDIFBMwIXOmbA925Wqj5YIGZLz+oI+E83YaOKYAcRPM54ciovoTxnFa4Lmrssu6C0mcsVc0W153DQ3mHGlScywSX8/V7NHoeSDLU5TgXZ5ZrFnBgnI6YpvPb4GYpTNz77aUDGb0EbRvQzBEKQgF5s33C/IpCfQIkZyDyiHhWOFlwVgEQTUuNi40YPuVO/BT6ri9JORIMi3OnCLoVR0xOqQzRHyDj8aLG2CvHw4vX70c3VIjzMBqeup2b6MCZyvcCapzqKvBNaYy/tOtI8MF4BfV64jD1RhSFSHm0EcVA7XNDYQJ6Ao=
