language: node_js
node_js:
- '8'
dist: trusty
sudo: false
branches:
  except:
  - results
install:
- npm install
script:
- npm run code-check
- npm run translate
- npm run build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: MY6IUcpd6lcwBuxgiBVqeVCH05deNWsrA4kmX2VxnXUKIlQqq9HvsP3NqunLtYQKt9SYWNPec0cXHZ0vhOGph9r7w14QWXwsYDbtIukiuqVGslsnGdnGFEgAzrT9Eskvk4lxP7bVc+uTc6ggKfVl3A4+eqI1kn1Scdr3kT4Q+AWrkfoKo74yvRcTYe++b6PMT+m9jjyNU9+zhiLaADyQHcbmU6HpKVnghykBw0hSl+t5j2sHOxS+aag5LnJHKu0xgsLNcgFu5sS1EJSzhGScp9O2LsznjbuWCRUO+rWsFlEbcgf+RtcQkvgbJheeMVQJ/UUmYxK31B1D7nxlbDlNq/AXyu2y8XBA2eQCn50oxVWLlbenudL6YWkCMmkpfKUIsfKT2Sb9tkkdLAXcEcZOLKnBz/QfhPKYEpbPCQ1t61cCvvgbQWGlwAYPO00KO/AbzEM7xG5+P9mvkzQEEO8lwthQUwTBCgsUh04HdkOnN3qmVfMQtjALdMIoV0ACCj5msXXEEbJ6MKMrXmZXpciykEokxkp8boh7TjAX2fUgBTYgOLj3gqz0GeQI33fjWWTADIjcIGQ2AGLrtNCQ/xcUuw46GY0ZCYYlbSoQ0bOUj0HCtY6fg7KMjUGkwzrTIYnWnQIE3WZqgQRHv2qGq9qpTpz05C3P98s53+7+lEu6cNg=
  on:
    branch: master
env:
  global:
  - secure: OH43g+O6Tueo+67Fj2m+pHcF0hUL+OKp2bkIqFTltrQ/AVZKwKIEOvWxsEqn4L3OUmCfR9y9pyRimv6x9JnZjLArb/DhvOSscVhWp02grQy4xOBYtYc5q5SlETz/MUbqJ7l9HWTF/YihuvTYSm2+jvsaO23PzQ1UdewvsQN9moEZ+H1e6Py+bscyjNhhOBI4W6vpWItKFAtnYG99fknad/JCP/n6x8MkCdWRXBmTghxqHJT/1NQdi9NG1V0oR3rzAQSvgSunuzt723XF3zGectM3iwDJuSFySwUe+Nb+r9eIoIYUNRXzvwKVMIRuCYnwd18fg/hWIV4bO19PIkkJhKt4/ebWEHLdB/5GXzwO8GdFqg3CKi2CIKI8COyvW9SvKIC9PrLrn6g7Ih6u+7EQoBe50oZNOStjFBdou0YZlHrAGEE3rqjgizag/K0kI+xrDYGWXAENqNA1oHTXcHROKbPI6iR6L4q+y0JxOjTTyxpWwu0eI5WFesEtPEX2ypDcuZkPzztuZnJoGyPcbzW7KYNyuNTi4Eor+hXVmf3OE71tewkHrgZw//Y1zOF7ZqC7YkfKRgN6i+m4BeKdJbaYLXBbkNzl6brS6jL6bg/bx2NQEDVhyI4UuOsLYC3fdmGfhOOcVIXoFFt9nbQ9W1/mM/HJyL5JPinUKULHlonLQks=
  - secure: XwGwQ+bx7p+438WqYMFMEVPtuRp/H8cdp74QHWYoOMfif8LiBJWBNsHEezDQMhscxHevIom9ZwdubatVGob7BZF21r+h/F+YX8eoWjNaCvfiv2XLRPkBU6sGP0PjwzVEBSt7Zi753IDuIeRM8CuhI7Qibe86Wya5h06z1C10uWn8arGinr74iSdqwXcFqraSl8ZjAYrg6qrlz4hZy6M/8RdrPFRVjnb4Ai5v4r2OfKKHfo3kpt1tvM+yQiXl6qAaI0laA4UJeaBvd9SFFtXzABz8bRBW24V2WqvBxRLp2s1jacWUsBJBvcgXK7drPH9xqP4SvUwYTC8mNraLokQvtzqt8tZ3ArBbao/upXK0b5AeO8TXPxdhCWjzOeDIFBMwIXOmbA925Wqj5YIGZLz+oI+E83YaOKYAcRPM54ciovoTxnFa4Lmrssu6C0mcsVc0W153DQ3mHGlScywSX8/V7NHoeSDLU5TgXZ5ZrFnBgnI6YpvPb4GYpTNz77aUDGb0EbRvQzBEKQgF5s33C/IpCfQIkZyDyiHhWOFlwVgEQTUuNi40YPuVO/BT6ri9JORIMi3OnCLoVR0xOqQzRHyDj8aLG2CvHw4vX70c3VIjzMBqeup2b6MCZyvcCapzqKvBNaYy/tOtI8MF4BfV64jD1RhSFSHm0EcVA7XNDYQJ6Ao=
